---
title: ""
output: html_document
---

<font size="5"> **MultSampSize:** Sample size estimation for mixed outcome endpoints </font>

Welcome to the GUI for sample size determination using latent variable models for mixed outcome endpoints. The app provides required sample sizes for co-primary, multiple primary and composite endpoints that are comprised of discrete and continuous measures. In the co-primary and multiple primary cases, the parameters can be inputted directly. In the case of composite endpoints, pilot data is used to provide parameter estimates. 

A tutorial on how to use the app, along with R code and example data, is available at <https://github.com/martinamcm/MultSampSize>. Further details on the methods implemented in this app are discussed in (McMenamin et al., 2019). 

<font size="4"> **References** </font>

McMenamin M, Barrett JK, Berglind A, Wason JMS. Sample Size Estimation using a Latent Variable Model for Mixed Outcome Co-Primary, Multiple Primary and Composite Endpoints. 2019; <https://arxiv.org/abs/1912.05258>

McMenamin M, Barrett JK, Berglind A, Wason JMS. Latent variable modelling for
complex composite endpoints. 2019; <https://arxiv.org/abs/1902.07037>

